# Generated by Django 4.1.2 on 2022-10-20 00:08

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id_asignatura', models.IntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('code_asignatura', models.CharField(max_length=7, verbose_name='code_asig')),
                ('nombre_asignatura', models.CharField(max_length=50, verbose_name='nombre_asig')),
            ],
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id_carrera', models.IntegerField(primary_key=True, serialize=False, verbose_name='id_carrera')),
                ('nombre_carrera', models.CharField(max_length=50, verbose_name='nombre_carrera')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('tipo', models.CharField(choices=[('P', 'Profesor'), ('A', 'Alumno')], max_length=1, verbose_name='tipo')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id_seccion', models.IntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('nom_seccion', models.CharField(max_length=4, verbose_name='id_secc')),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Secciones_asignatura', to='Data.asignatura')),
            ],
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumno', models.ForeignKey(limit_choices_to={'tipo': 'A'}, on_delete=django.db.models.deletion.CASCADE, related_name='matriculados_alumno', to=settings.AUTH_USER_MODEL)),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculados_secion', to='Data.seccion')),
            ],
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id_clase', models.IntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('fecha_clase', models.DateField(auto_now_add=True, verbose_name='fecha_clase')),
                ('esta_presente', models.BooleanField(default=False, verbose_name='Presente')),
                ('id_alumno', models.ForeignKey(limit_choices_to={'tipo': 'A'}, on_delete=django.db.models.deletion.CASCADE, related_name='asistentes_alumno', to=settings.AUTH_USER_MODEL)),
                ('id_seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistentes_secion', to='Data.seccion')),
            ],
        ),
        migrations.AddField(
            model_name='asignatura',
            name='id_carrera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaturas_carrera', to='Data.carrera'),
        ),
        migrations.AddField(
            model_name='asignatura',
            name='profesores',
            field=models.ForeignKey(limit_choices_to={'tipo': 'P'}, on_delete=django.db.models.deletion.CASCADE, related_name='asignaturas_profesores', to=settings.AUTH_USER_MODEL),
        ),
    ]
