# Generated by Django 3.2.16 on 2022-10-20 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrera',
            name='escuela',
            field=models.CharField(default='Informatica', max_length=50, verbose_name='escuela'),
        ),
    ]
